# Generated by Django 3.2 on 2021-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('button_txt', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/slider/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
