# Generated by Django 3.2 on 2021-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='btn_link',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
