# Generated by Django 3.2.2 on 2021-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210512_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Canon', 'Canon'), ('Sony', 'Sony'), ('Nikon', 'Nikon'), ('Red', 'Red'), ('Fuji', 'Fuji'), ('Gopro', 'Gopro'), ('Other', 'Other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Code', 'Code'), ('Mobile Review', 'Mobile Review'), ('Vlogs', 'Vlogs'), ('Comedy', 'Comedy'), ('Gaming', 'Gaming'), ('Films', 'Films'), ('Cooking', 'Cooking'), ('Others', 'Others')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Small', 'Small'), ('Large', 'Large')], max_length=250),
        ),
    ]
